name: Deploy Node.js App without Build Step

on:
  push:
    branches:
      - main # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Install dependencies
#        run: npm install

      - name: copy dist file with scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets._HOST }}
          username: ${{ secrets._USERNAME }}
          password: ${{ secrets._PASSWORD }}
          port: ${{ secrets._PORT }}
          source: './'
          target: '/opt/fsm-web'

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets._HOST }}
          username: ${{ secrets._USERNAME }}
          password: ${{ secrets._PASSWORD }}
          script: |
            # 切换到你的应用目录  
            cd /opt/fsm-web
            
            # 停止当前运行的应用（如果有的话）  
            # pm2 stop your-app-name || true # 假设你使用PM2管理应用  
            # 或者  
            # killall node || true # 停止所有node进程  
            
            # 清除旧的node_modules目录和package-lock.json文件（可选）  
            # rm -rf node_modules package-lock.json  
            rm -rf node_modules
            
            # 从GitHub复制最新的代码到服务器  
            rsync -avz --delete ./ ${username}@${host}:/opt/fsm-web/
            
            # 在服务器上安装依赖  
            ssh ${username}@${host} "cd /opt/fsm-web/ && npm install"  
            
            # 启动你的Node.js应用  
            ssh ${username}@${host} "cd /opt/fsm-web/ && npm start"
